title: Weijie Zhang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>PhD candidate with **Dr. Martin Jung**, **Dr. Jacob Nelson**, and **Prof. Dr. Markus Reichstein** in <a href="https://www.bgc-jena.mpg.de/en">MPI-BGC</a>, and with **Prof. Dr. Diego Miralles** in <a href="https://www.ugent.be/bw/environment/en/research/h-cel">Ghent University</a><br>
  <br>Working on water flux, water-carbon coupling with data from Eddy Covariance measurements and FLUXCOM, etc.<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
